title: PHP React MVC Template
description: A modern PHP template with Laravel-style MVC architecture and React SPA integration
url: https://awaismehnga.github.io
baseurl: /php-react-starter-template

# Theme
remote_theme: just-the-docs/just-the-docs

# Color scheme
color_scheme: light

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/AwaisMehnga/php-react-starter-template

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3

# Mermaid support
mermaid:
  version: "9.1.6"

# Code highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Footer
footer_content: "Copyright &copy; 2025 PHP React MVC Template. Distributed under the <a href=\"https://github.com/AwaisMehnga/php-react-starter-template/blob/main/LICENSE\">MIT License</a>."

# Exclude from processing
exclude:
  - node_modules/
  - vendor/
  - app/
  - build/
  - modules/
  - views/
  - routes/
  - config/
  - database/
  - public/
  - "*.php"
  - "*.json"
  - "*.js"
  - Gemfile
  - Gemfile.lock
